/**
 * NextConfig
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.nextresources.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * AutoNumberingGenerateRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-28T02:31:31.507+05:30")
public class AutoNumberingGenerateRequest   {
  @SerializedName("subType")
  private Long subType = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    @SerializedName("VoucherNo")
    VOUCHERNO("VoucherNo"),
    
    @SerializedName("AdmissionRegistrationNo")
    ADMISSIONREGISTRATIONNO("AdmissionRegistrationNo"),
    
    @SerializedName("ReceiptNo")
    RECEIPTNO("ReceiptNo"),
    
    @SerializedName("AccessionNo")
    ACCESSIONNO("AccessionNo"),
    
    @SerializedName("ResourceNo")
    RESOURCENO("ResourceNo"),
    
    @SerializedName("LetterFormatNo")
    LETTERFORMATNO("LetterFormatNo"),
    
    @SerializedName("BankRefNo")
    BANKREFNO("BankRefNo"),
    
    @SerializedName("LeavePassNo")
    LEAVEPASSNO("LeavePassNo"),
    
    @SerializedName("AdmissionStep")
    ADMISSIONSTEP("AdmissionStep"),
    
    @SerializedName("ChallanNo")
    CHALLANNO("ChallanNo"),
    
    @SerializedName("ItemNo")
    ITEMNO("ItemNo"),
    
    @SerializedName("PurchaseOrderNo")
    PURCHASEORDERNO("PurchaseOrderNo"),
    
    @SerializedName("InventoryReceiptsNo")
    INVENTORYRECEIPTSNO("InventoryReceiptsNo"),
    
    @SerializedName("LibMembershipNo")
    LIBMEMBERSHIPNO("LibMembershipNo"),
    
    @SerializedName("employeeId")
    EMPLOYEEID("employeeId"),
    
    @SerializedName("EnquiryNo")
    ENQUIRYNO("EnquiryNo"),
    
    @SerializedName("Ledger_Code")
    LEDGER_CODE("Ledger_Code"),
    
    @SerializedName("Group_Code")
    GROUP_CODE("Group_Code"),
    
    @SerializedName("AdmissionOnlineFeePayment")
    ADMISSIONONLINEFEEPAYMENT("AdmissionOnlineFeePayment"),
    
    @SerializedName("VisitorPass")
    VISITORPASS("VisitorPass");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  public AutoNumberingGenerateRequest subType(Long subType) {
    this.subType = subType;
    return this;
  }

   /**
   * Get subType
   * @return subType
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSubType() {
    return subType;
  }

  public void setSubType(Long subType) {
    this.subType = subType;
  }

  public AutoNumberingGenerateRequest type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoNumberingGenerateRequest autoNumberingGenerateRequest = (AutoNumberingGenerateRequest) o;
    return Objects.equals(this.subType, autoNumberingGenerateRequest.subType) &&
        Objects.equals(this.type, autoNumberingGenerateRequest.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subType, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoNumberingGenerateRequest {\n");
    
    sb.append("    subType: ").append(toIndentedString(subType)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

