/**
 * NextConfig
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.nextresources.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.nextresources.model.SubjectResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * ChapterResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-28T02:31:31.507+05:30")
public class ChapterResponse   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("chapterName")
  private String chapterName = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("subjectResponse")
  private SubjectResponse subjectResponse = null;

  @SerializedName("error")
  private Boolean error = false;

  @SerializedName("reason")
  private List<String> reason = new ArrayList<String>();

  public ChapterResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ChapterResponse chapterName(String chapterName) {
    this.chapterName = chapterName;
    return this;
  }

   /**
   * Get chapterName
   * @return chapterName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getChapterName() {
    return chapterName;
  }

  public void setChapterName(String chapterName) {
    this.chapterName = chapterName;
  }

  public ChapterResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ChapterResponse subjectResponse(SubjectResponse subjectResponse) {
    this.subjectResponse = subjectResponse;
    return this;
  }

   /**
   * Get subjectResponse
   * @return subjectResponse
  **/
  @ApiModelProperty(example = "null", value = "")
  public SubjectResponse getSubjectResponse() {
    return subjectResponse;
  }

  public void setSubjectResponse(SubjectResponse subjectResponse) {
    this.subjectResponse = subjectResponse;
  }

  public ChapterResponse error(Boolean error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getError() {
    return error;
  }

  public void setError(Boolean error) {
    this.error = error;
  }

  public ChapterResponse reason(List<String> reason) {
    this.reason = reason;
    return this;
  }

  public ChapterResponse addReasonItem(String reasonItem) {
    this.reason.add(reasonItem);
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getReason() {
    return reason;
  }

  public void setReason(List<String> reason) {
    this.reason = reason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChapterResponse chapterResponse = (ChapterResponse) o;
    return Objects.equals(this.id, chapterResponse.id) &&
        Objects.equals(this.chapterName, chapterResponse.chapterName) &&
        Objects.equals(this.description, chapterResponse.description) &&
        Objects.equals(this.subjectResponse, chapterResponse.subjectResponse) &&
        Objects.equals(this.error, chapterResponse.error) &&
        Objects.equals(this.reason, chapterResponse.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, chapterName, description, subjectResponse, error, reason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChapterResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    chapterName: ").append(toIndentedString(chapterName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    subjectResponse: ").append(toIndentedString(subjectResponse)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

