/**
 * NextConfig
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.nextresources.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;


/**
 * CustomFieldDataShortDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-28T02:31:31.507+05:30")
public class CustomFieldDataShortDTO   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("customFieldId")
  private Long customFieldId = null;

  @SerializedName("entityInstanceId")
  private Long entityInstanceId = null;

  @SerializedName("value")
  private String value = null;

  @SerializedName("createdBy")
  private Long createdBy = null;

  @SerializedName("createdOn")
  private Date createdOn = null;

  @SerializedName("modifiedBy")
  private Long modifiedBy = null;

  @SerializedName("modifiedOn")
  private Date modifiedOn = null;

  public CustomFieldDataShortDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public CustomFieldDataShortDTO customFieldId(Long customFieldId) {
    this.customFieldId = customFieldId;
    return this;
  }

   /**
   * Get customFieldId
   * @return customFieldId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCustomFieldId() {
    return customFieldId;
  }

  public void setCustomFieldId(Long customFieldId) {
    this.customFieldId = customFieldId;
  }

  public CustomFieldDataShortDTO entityInstanceId(Long entityInstanceId) {
    this.entityInstanceId = entityInstanceId;
    return this;
  }

   /**
   * Get entityInstanceId
   * @return entityInstanceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getEntityInstanceId() {
    return entityInstanceId;
  }

  public void setEntityInstanceId(Long entityInstanceId) {
    this.entityInstanceId = entityInstanceId;
  }

  public CustomFieldDataShortDTO value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public CustomFieldDataShortDTO createdBy(Long createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(Long createdBy) {
    this.createdBy = createdBy;
  }

  public CustomFieldDataShortDTO createdOn(Date createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(Date createdOn) {
    this.createdOn = createdOn;
  }

  public CustomFieldDataShortDTO modifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public CustomFieldDataShortDTO modifiedOn(Date modifiedOn) {
    this.modifiedOn = modifiedOn;
    return this;
  }

   /**
   * Get modifiedOn
   * @return modifiedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getModifiedOn() {
    return modifiedOn;
  }

  public void setModifiedOn(Date modifiedOn) {
    this.modifiedOn = modifiedOn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomFieldDataShortDTO customFieldDataShortDTO = (CustomFieldDataShortDTO) o;
    return Objects.equals(this.id, customFieldDataShortDTO.id) &&
        Objects.equals(this.customFieldId, customFieldDataShortDTO.customFieldId) &&
        Objects.equals(this.entityInstanceId, customFieldDataShortDTO.entityInstanceId) &&
        Objects.equals(this.value, customFieldDataShortDTO.value) &&
        Objects.equals(this.createdBy, customFieldDataShortDTO.createdBy) &&
        Objects.equals(this.createdOn, customFieldDataShortDTO.createdOn) &&
        Objects.equals(this.modifiedBy, customFieldDataShortDTO.modifiedBy) &&
        Objects.equals(this.modifiedOn, customFieldDataShortDTO.modifiedOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, customFieldId, entityInstanceId, value, createdBy, createdOn, modifiedBy, modifiedOn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomFieldDataShortDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    customFieldId: ").append(toIndentedString(customFieldId)).append("\n");
    sb.append("    entityInstanceId: ").append(toIndentedString(entityInstanceId)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    modifiedOn: ").append(toIndentedString(modifiedOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

