/**
 * NextConfig
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.nextresources.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.nextresources.model.CustomFieldResponse;
import com.nexteducation.nextresources.model.FormResponse;
import com.nexteducation.nextresources.model.StandardFieldResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;


/**
 * CustomFormElementResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-28T02:31:31.507+05:30")
public class CustomFormElementResponse   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("branchId")
  private Long branchId = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("placeholder")
  private String placeholder = null;

  @SerializedName("customField")
  private CustomFieldResponse customField = null;

  @SerializedName("form")
  private FormResponse form = null;

  @SerializedName("entityName")
  private String entityName = null;

  @SerializedName("standardField")
  private StandardFieldResponse standardField = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("Active")
    ACTIVE("Active"),
    
    @SerializedName("Inactive")
    INACTIVE("Inactive");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("ifMandatory")
  private Boolean ifMandatory = false;

  @SerializedName("ifHide")
  private Boolean ifHide = false;

  @SerializedName("createdBy")
  private Long createdBy = null;

  @SerializedName("createdOn")
  private Date createdOn = null;

  @SerializedName("modifiedBy")
  private Long modifiedBy = null;

  @SerializedName("modifiedOn")
  private Date modifiedOn = null;

  @SerializedName("systemMandatory")
  private Boolean systemMandatory = false;

  /**
   * Gets or Sets fieldType
   */
  public enum FieldTypeEnum {
    @SerializedName("Checkbox")
    CHECKBOX("Checkbox"),
    
    @SerializedName("Color")
    COLOR("Color"),
    
    @SerializedName("Date")
    DATE("Date"),
    
    @SerializedName("Datetime")
    DATETIME("Datetime"),
    
    @SerializedName("Email")
    EMAIL("Email"),
    
    @SerializedName("File")
    FILE("File"),
    
    @SerializedName("Hidden")
    HIDDEN("Hidden"),
    
    @SerializedName("Image")
    IMAGE("Image"),
    
    @SerializedName("List")
    LIST("List"),
    
    @SerializedName("MultiSelect")
    MULTISELECT("MultiSelect"),
    
    @SerializedName("Number")
    NUMBER("Number"),
    
    @SerializedName("Password")
    PASSWORD("Password"),
    
    @SerializedName("Paragraph")
    PARAGRAPH("Paragraph"),
    
    @SerializedName("Radio")
    RADIO("Radio"),
    
    @SerializedName("Range")
    RANGE("Range"),
    
    @SerializedName("Text")
    TEXT("Text"),
    
    @SerializedName("Time")
    TIME("Time"),
    
    @SerializedName("Url")
    URL("Url");

    private String value;

    FieldTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("fieldType")
  private FieldTypeEnum fieldType = null;

  @SerializedName("standardFieldId")
  private Long standardFieldId = null;

  public CustomFormElementResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public CustomFormElementResponse branchId(Long branchId) {
    this.branchId = branchId;
    return this;
  }

   /**
   * Get branchId
   * @return branchId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBranchId() {
    return branchId;
  }

  public void setBranchId(Long branchId) {
    this.branchId = branchId;
  }

  public CustomFormElementResponse label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public CustomFormElementResponse placeholder(String placeholder) {
    this.placeholder = placeholder;
    return this;
  }

   /**
   * Get placeholder
   * @return placeholder
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPlaceholder() {
    return placeholder;
  }

  public void setPlaceholder(String placeholder) {
    this.placeholder = placeholder;
  }

  public CustomFormElementResponse customField(CustomFieldResponse customField) {
    this.customField = customField;
    return this;
  }

   /**
   * Get customField
   * @return customField
  **/
  @ApiModelProperty(example = "null", value = "")
  public CustomFieldResponse getCustomField() {
    return customField;
  }

  public void setCustomField(CustomFieldResponse customField) {
    this.customField = customField;
  }

  public CustomFormElementResponse form(FormResponse form) {
    this.form = form;
    return this;
  }

   /**
   * Get form
   * @return form
  **/
  @ApiModelProperty(example = "null", value = "")
  public FormResponse getForm() {
    return form;
  }

  public void setForm(FormResponse form) {
    this.form = form;
  }

  public CustomFormElementResponse entityName(String entityName) {
    this.entityName = entityName;
    return this;
  }

   /**
   * Get entityName
   * @return entityName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEntityName() {
    return entityName;
  }

  public void setEntityName(String entityName) {
    this.entityName = entityName;
  }

  public CustomFormElementResponse standardField(StandardFieldResponse standardField) {
    this.standardField = standardField;
    return this;
  }

   /**
   * Get standardField
   * @return standardField
  **/
  @ApiModelProperty(example = "null", value = "")
  public StandardFieldResponse getStandardField() {
    return standardField;
  }

  public void setStandardField(StandardFieldResponse standardField) {
    this.standardField = standardField;
  }

  public CustomFormElementResponse status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public CustomFormElementResponse ifMandatory(Boolean ifMandatory) {
    this.ifMandatory = ifMandatory;
    return this;
  }

   /**
   * Get ifMandatory
   * @return ifMandatory
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIfMandatory() {
    return ifMandatory;
  }

  public void setIfMandatory(Boolean ifMandatory) {
    this.ifMandatory = ifMandatory;
  }

  public CustomFormElementResponse ifHide(Boolean ifHide) {
    this.ifHide = ifHide;
    return this;
  }

   /**
   * Get ifHide
   * @return ifHide
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIfHide() {
    return ifHide;
  }

  public void setIfHide(Boolean ifHide) {
    this.ifHide = ifHide;
  }

  public CustomFormElementResponse createdBy(Long createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(Long createdBy) {
    this.createdBy = createdBy;
  }

  public CustomFormElementResponse createdOn(Date createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(Date createdOn) {
    this.createdOn = createdOn;
  }

  public CustomFormElementResponse modifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public CustomFormElementResponse modifiedOn(Date modifiedOn) {
    this.modifiedOn = modifiedOn;
    return this;
  }

   /**
   * Get modifiedOn
   * @return modifiedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getModifiedOn() {
    return modifiedOn;
  }

  public void setModifiedOn(Date modifiedOn) {
    this.modifiedOn = modifiedOn;
  }

  public CustomFormElementResponse systemMandatory(Boolean systemMandatory) {
    this.systemMandatory = systemMandatory;
    return this;
  }

   /**
   * Get systemMandatory
   * @return systemMandatory
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSystemMandatory() {
    return systemMandatory;
  }

  public void setSystemMandatory(Boolean systemMandatory) {
    this.systemMandatory = systemMandatory;
  }

  public CustomFormElementResponse fieldType(FieldTypeEnum fieldType) {
    this.fieldType = fieldType;
    return this;
  }

   /**
   * Get fieldType
   * @return fieldType
  **/
  @ApiModelProperty(example = "null", value = "")
  public FieldTypeEnum getFieldType() {
    return fieldType;
  }

  public void setFieldType(FieldTypeEnum fieldType) {
    this.fieldType = fieldType;
  }

  public CustomFormElementResponse standardFieldId(Long standardFieldId) {
    this.standardFieldId = standardFieldId;
    return this;
  }

   /**
   * Get standardFieldId
   * @return standardFieldId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStandardFieldId() {
    return standardFieldId;
  }

  public void setStandardFieldId(Long standardFieldId) {
    this.standardFieldId = standardFieldId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomFormElementResponse customFormElementResponse = (CustomFormElementResponse) o;
    return Objects.equals(this.id, customFormElementResponse.id) &&
        Objects.equals(this.branchId, customFormElementResponse.branchId) &&
        Objects.equals(this.label, customFormElementResponse.label) &&
        Objects.equals(this.placeholder, customFormElementResponse.placeholder) &&
        Objects.equals(this.customField, customFormElementResponse.customField) &&
        Objects.equals(this.form, customFormElementResponse.form) &&
        Objects.equals(this.entityName, customFormElementResponse.entityName) &&
        Objects.equals(this.standardField, customFormElementResponse.standardField) &&
        Objects.equals(this.status, customFormElementResponse.status) &&
        Objects.equals(this.ifMandatory, customFormElementResponse.ifMandatory) &&
        Objects.equals(this.ifHide, customFormElementResponse.ifHide) &&
        Objects.equals(this.createdBy, customFormElementResponse.createdBy) &&
        Objects.equals(this.createdOn, customFormElementResponse.createdOn) &&
        Objects.equals(this.modifiedBy, customFormElementResponse.modifiedBy) &&
        Objects.equals(this.modifiedOn, customFormElementResponse.modifiedOn) &&
        Objects.equals(this.systemMandatory, customFormElementResponse.systemMandatory) &&
        Objects.equals(this.fieldType, customFormElementResponse.fieldType) &&
        Objects.equals(this.standardFieldId, customFormElementResponse.standardFieldId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, branchId, label, placeholder, customField, form, entityName, standardField, status, ifMandatory, ifHide, createdBy, createdOn, modifiedBy, modifiedOn, systemMandatory, fieldType, standardFieldId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomFormElementResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    branchId: ").append(toIndentedString(branchId)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    placeholder: ").append(toIndentedString(placeholder)).append("\n");
    sb.append("    customField: ").append(toIndentedString(customField)).append("\n");
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("    entityName: ").append(toIndentedString(entityName)).append("\n");
    sb.append("    standardField: ").append(toIndentedString(standardField)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    ifMandatory: ").append(toIndentedString(ifMandatory)).append("\n");
    sb.append("    ifHide: ").append(toIndentedString(ifHide)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    modifiedOn: ").append(toIndentedString(modifiedOn)).append("\n");
    sb.append("    systemMandatory: ").append(toIndentedString(systemMandatory)).append("\n");
    sb.append("    fieldType: ").append(toIndentedString(fieldType)).append("\n");
    sb.append("    standardFieldId: ").append(toIndentedString(standardFieldId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

