/**
 * NextConfig
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.nextresources.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * CustomQuestionResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-28T02:31:31.507+05:30")
public class CustomQuestionResponse   {
  @SerializedName("correct")
  private Integer correct = null;

  @SerializedName("wrong")
  private Integer wrong = null;

  @SerializedName("badge")
  private String badge = null;

  public CustomQuestionResponse correct(Integer correct) {
    this.correct = correct;
    return this;
  }

   /**
   * Get correct
   * @return correct
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCorrect() {
    return correct;
  }

  public void setCorrect(Integer correct) {
    this.correct = correct;
  }

  public CustomQuestionResponse wrong(Integer wrong) {
    this.wrong = wrong;
    return this;
  }

   /**
   * Get wrong
   * @return wrong
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWrong() {
    return wrong;
  }

  public void setWrong(Integer wrong) {
    this.wrong = wrong;
  }

  public CustomQuestionResponse badge(String badge) {
    this.badge = badge;
    return this;
  }

   /**
   * Get badge
   * @return badge
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBadge() {
    return badge;
  }

  public void setBadge(String badge) {
    this.badge = badge;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomQuestionResponse customQuestionResponse = (CustomQuestionResponse) o;
    return Objects.equals(this.correct, customQuestionResponse.correct) &&
        Objects.equals(this.wrong, customQuestionResponse.wrong) &&
        Objects.equals(this.badge, customQuestionResponse.badge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(correct, wrong, badge);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomQuestionResponse {\n");
    
    sb.append("    correct: ").append(toIndentedString(correct)).append("\n");
    sb.append("    wrong: ").append(toIndentedString(wrong)).append("\n");
    sb.append("    badge: ").append(toIndentedString(badge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

