/**
 * NextConfig
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.nextresources.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.nextresources.model.ChapterResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * MindMapResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-28T02:31:31.507+05:30")
public class MindMapResponse   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("parentChapter")
  private ChapterResponse parentChapter = null;

  @SerializedName("chapter")
  private ChapterResponse chapter = null;

  public MindMapResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public MindMapResponse parentChapter(ChapterResponse parentChapter) {
    this.parentChapter = parentChapter;
    return this;
  }

   /**
   * Get parentChapter
   * @return parentChapter
  **/
  @ApiModelProperty(example = "null", value = "")
  public ChapterResponse getParentChapter() {
    return parentChapter;
  }

  public void setParentChapter(ChapterResponse parentChapter) {
    this.parentChapter = parentChapter;
  }

  public MindMapResponse chapter(ChapterResponse chapter) {
    this.chapter = chapter;
    return this;
  }

   /**
   * Get chapter
   * @return chapter
  **/
  @ApiModelProperty(example = "null", value = "")
  public ChapterResponse getChapter() {
    return chapter;
  }

  public void setChapter(ChapterResponse chapter) {
    this.chapter = chapter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MindMapResponse mindMapResponse = (MindMapResponse) o;
    return Objects.equals(this.id, mindMapResponse.id) &&
        Objects.equals(this.parentChapter, mindMapResponse.parentChapter) &&
        Objects.equals(this.chapter, mindMapResponse.chapter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, parentChapter, chapter);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MindMapResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parentChapter: ").append(toIndentedString(parentChapter)).append("\n");
    sb.append("    chapter: ").append(toIndentedString(chapter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

