/**
 * NextConfig
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.nextresources.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ProductFeatureAddRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-28T02:31:31.507+05:30")
public class ProductFeatureAddRequest   {
  @SerializedName("featureDesc")
  private String featureDesc = null;

  @SerializedName("featureValue")
  private String featureValue = null;

  @SerializedName("createdBy")
  private String createdBy = null;

  @SerializedName("modifiedBy")
  private String modifiedBy = null;

  public ProductFeatureAddRequest featureDesc(String featureDesc) {
    this.featureDesc = featureDesc;
    return this;
  }

   /**
   * Get featureDesc
   * @return featureDesc
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFeatureDesc() {
    return featureDesc;
  }

  public void setFeatureDesc(String featureDesc) {
    this.featureDesc = featureDesc;
  }

  public ProductFeatureAddRequest featureValue(String featureValue) {
    this.featureValue = featureValue;
    return this;
  }

   /**
   * Get featureValue
   * @return featureValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFeatureValue() {
    return featureValue;
  }

  public void setFeatureValue(String featureValue) {
    this.featureValue = featureValue;
  }

  public ProductFeatureAddRequest createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public ProductFeatureAddRequest modifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductFeatureAddRequest productFeatureAddRequest = (ProductFeatureAddRequest) o;
    return Objects.equals(this.featureDesc, productFeatureAddRequest.featureDesc) &&
        Objects.equals(this.featureValue, productFeatureAddRequest.featureValue) &&
        Objects.equals(this.createdBy, productFeatureAddRequest.createdBy) &&
        Objects.equals(this.modifiedBy, productFeatureAddRequest.modifiedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(featureDesc, featureValue, createdBy, modifiedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductFeatureAddRequest {\n");
    
    sb.append("    featureDesc: ").append(toIndentedString(featureDesc)).append("\n");
    sb.append("    featureValue: ").append(toIndentedString(featureValue)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

