/**
 * NextConfig
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.nextresources.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ProductFeatureUpdateRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-28T02:31:31.507+05:30")
public class ProductFeatureUpdateRequest   {
  @SerializedName("branchId")
  private Long branchId = null;

  @SerializedName("featureDesc")
  private String featureDesc = null;

  @SerializedName("featureValue")
  private String featureValue = null;

  @SerializedName("modifiedBy")
  private String modifiedBy = null;

  @SerializedName("id")
  private Long id = null;

  public ProductFeatureUpdateRequest branchId(Long branchId) {
    this.branchId = branchId;
    return this;
  }

   /**
   * Get branchId
   * @return branchId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBranchId() {
    return branchId;
  }

  public void setBranchId(Long branchId) {
    this.branchId = branchId;
  }

  public ProductFeatureUpdateRequest featureDesc(String featureDesc) {
    this.featureDesc = featureDesc;
    return this;
  }

   /**
   * Get featureDesc
   * @return featureDesc
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFeatureDesc() {
    return featureDesc;
  }

  public void setFeatureDesc(String featureDesc) {
    this.featureDesc = featureDesc;
  }

  public ProductFeatureUpdateRequest featureValue(String featureValue) {
    this.featureValue = featureValue;
    return this;
  }

   /**
   * Get featureValue
   * @return featureValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFeatureValue() {
    return featureValue;
  }

  public void setFeatureValue(String featureValue) {
    this.featureValue = featureValue;
  }

  public ProductFeatureUpdateRequest modifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public ProductFeatureUpdateRequest id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductFeatureUpdateRequest productFeatureUpdateRequest = (ProductFeatureUpdateRequest) o;
    return Objects.equals(this.branchId, productFeatureUpdateRequest.branchId) &&
        Objects.equals(this.featureDesc, productFeatureUpdateRequest.featureDesc) &&
        Objects.equals(this.featureValue, productFeatureUpdateRequest.featureValue) &&
        Objects.equals(this.modifiedBy, productFeatureUpdateRequest.modifiedBy) &&
        Objects.equals(this.id, productFeatureUpdateRequest.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(branchId, featureDesc, featureValue, modifiedBy, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductFeatureUpdateRequest {\n");
    
    sb.append("    branchId: ").append(toIndentedString(branchId)).append("\n");
    sb.append("    featureDesc: ").append(toIndentedString(featureDesc)).append("\n");
    sb.append("    featureValue: ").append(toIndentedString(featureValue)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

