/**
 * NextConfig
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.nextresources.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;


/**
 * StandardFieldResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-28T02:31:31.507+05:30")
public class StandardFieldResponse   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("branchId")
  private Long branchId = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("entityName")
  private String entityName = null;

  /**
   * Gets or Sets fieldType
   */
  public enum FieldTypeEnum {
    @SerializedName("Checkbox")
    CHECKBOX("Checkbox"),
    
    @SerializedName("Color")
    COLOR("Color"),
    
    @SerializedName("Date")
    DATE("Date"),
    
    @SerializedName("Datetime")
    DATETIME("Datetime"),
    
    @SerializedName("Email")
    EMAIL("Email"),
    
    @SerializedName("File")
    FILE("File"),
    
    @SerializedName("Hidden")
    HIDDEN("Hidden"),
    
    @SerializedName("Image")
    IMAGE("Image"),
    
    @SerializedName("List")
    LIST("List"),
    
    @SerializedName("MultiSelect")
    MULTISELECT("MultiSelect"),
    
    @SerializedName("Number")
    NUMBER("Number"),
    
    @SerializedName("Password")
    PASSWORD("Password"),
    
    @SerializedName("Paragraph")
    PARAGRAPH("Paragraph"),
    
    @SerializedName("Radio")
    RADIO("Radio"),
    
    @SerializedName("Range")
    RANGE("Range"),
    
    @SerializedName("Text")
    TEXT("Text"),
    
    @SerializedName("Time")
    TIME("Time"),
    
    @SerializedName("Url")
    URL("Url");

    private String value;

    FieldTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("fieldType")
  private FieldTypeEnum fieldType = null;

  /**
   * Gets or Sets inputType
   */
  public enum InputTypeEnum {
    @SerializedName("String")
    STRING("String"),
    
    @SerializedName("Number")
    NUMBER("Number");

    private String value;

    InputTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("inputType")
  private InputTypeEnum inputType = null;

  @SerializedName("key")
  private String key = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("Active")
    ACTIVE("Active"),
    
    @SerializedName("Inactive")
    INACTIVE("Inactive");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("createdBy")
  private Long createdBy = null;

  @SerializedName("createdOn")
  private Date createdOn = null;

  @SerializedName("modifiedBy")
  private Long modifiedBy = null;

  @SerializedName("modifiedOn")
  private Date modifiedOn = null;

  @SerializedName("systemMandatory")
  private Boolean systemMandatory = false;

  public StandardFieldResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public StandardFieldResponse branchId(Long branchId) {
    this.branchId = branchId;
    return this;
  }

   /**
   * Get branchId
   * @return branchId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBranchId() {
    return branchId;
  }

  public void setBranchId(Long branchId) {
    this.branchId = branchId;
  }

  public StandardFieldResponse label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public StandardFieldResponse entityName(String entityName) {
    this.entityName = entityName;
    return this;
  }

   /**
   * Get entityName
   * @return entityName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEntityName() {
    return entityName;
  }

  public void setEntityName(String entityName) {
    this.entityName = entityName;
  }

  public StandardFieldResponse fieldType(FieldTypeEnum fieldType) {
    this.fieldType = fieldType;
    return this;
  }

   /**
   * Get fieldType
   * @return fieldType
  **/
  @ApiModelProperty(example = "null", value = "")
  public FieldTypeEnum getFieldType() {
    return fieldType;
  }

  public void setFieldType(FieldTypeEnum fieldType) {
    this.fieldType = fieldType;
  }

  public StandardFieldResponse inputType(InputTypeEnum inputType) {
    this.inputType = inputType;
    return this;
  }

   /**
   * Get inputType
   * @return inputType
  **/
  @ApiModelProperty(example = "null", value = "")
  public InputTypeEnum getInputType() {
    return inputType;
  }

  public void setInputType(InputTypeEnum inputType) {
    this.inputType = inputType;
  }

  public StandardFieldResponse key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public StandardFieldResponse status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public StandardFieldResponse createdBy(Long createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(Long createdBy) {
    this.createdBy = createdBy;
  }

  public StandardFieldResponse createdOn(Date createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(Date createdOn) {
    this.createdOn = createdOn;
  }

  public StandardFieldResponse modifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(Long modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public StandardFieldResponse modifiedOn(Date modifiedOn) {
    this.modifiedOn = modifiedOn;
    return this;
  }

   /**
   * Get modifiedOn
   * @return modifiedOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getModifiedOn() {
    return modifiedOn;
  }

  public void setModifiedOn(Date modifiedOn) {
    this.modifiedOn = modifiedOn;
  }

  public StandardFieldResponse systemMandatory(Boolean systemMandatory) {
    this.systemMandatory = systemMandatory;
    return this;
  }

   /**
   * Get systemMandatory
   * @return systemMandatory
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSystemMandatory() {
    return systemMandatory;
  }

  public void setSystemMandatory(Boolean systemMandatory) {
    this.systemMandatory = systemMandatory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StandardFieldResponse standardFieldResponse = (StandardFieldResponse) o;
    return Objects.equals(this.id, standardFieldResponse.id) &&
        Objects.equals(this.branchId, standardFieldResponse.branchId) &&
        Objects.equals(this.label, standardFieldResponse.label) &&
        Objects.equals(this.entityName, standardFieldResponse.entityName) &&
        Objects.equals(this.fieldType, standardFieldResponse.fieldType) &&
        Objects.equals(this.inputType, standardFieldResponse.inputType) &&
        Objects.equals(this.key, standardFieldResponse.key) &&
        Objects.equals(this.status, standardFieldResponse.status) &&
        Objects.equals(this.createdBy, standardFieldResponse.createdBy) &&
        Objects.equals(this.createdOn, standardFieldResponse.createdOn) &&
        Objects.equals(this.modifiedBy, standardFieldResponse.modifiedBy) &&
        Objects.equals(this.modifiedOn, standardFieldResponse.modifiedOn) &&
        Objects.equals(this.systemMandatory, standardFieldResponse.systemMandatory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, branchId, label, entityName, fieldType, inputType, key, status, createdBy, createdOn, modifiedBy, modifiedOn, systemMandatory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandardFieldResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    branchId: ").append(toIndentedString(branchId)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    entityName: ").append(toIndentedString(entityName)).append("\n");
    sb.append("    fieldType: ").append(toIndentedString(fieldType)).append("\n");
    sb.append("    inputType: ").append(toIndentedString(inputType)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    modifiedOn: ").append(toIndentedString(modifiedOn)).append("\n");
    sb.append("    systemMandatory: ").append(toIndentedString(systemMandatory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

