/**
 * NextConfig
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.nexteducation.nextresources.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.nexteducation.nextresources.model.StaffResponse;
import com.nexteducation.nextresources.model.StudyClassResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * SubjectResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-28T02:31:31.507+05:30")
public class SubjectResponse   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("subjectName")
  private String subjectName = null;

  @SerializedName("staffResponese")
  private StaffResponse staffResponese = null;

  @SerializedName("studyClassResponse")
  private StudyClassResponse studyClassResponse = null;

  public SubjectResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SubjectResponse subjectName(String subjectName) {
    this.subjectName = subjectName;
    return this;
  }

   /**
   * Get subjectName
   * @return subjectName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSubjectName() {
    return subjectName;
  }

  public void setSubjectName(String subjectName) {
    this.subjectName = subjectName;
  }

  public SubjectResponse staffResponese(StaffResponse staffResponese) {
    this.staffResponese = staffResponese;
    return this;
  }

   /**
   * Get staffResponese
   * @return staffResponese
  **/
  @ApiModelProperty(example = "null", value = "")
  public StaffResponse getStaffResponese() {
    return staffResponese;
  }

  public void setStaffResponese(StaffResponse staffResponese) {
    this.staffResponese = staffResponese;
  }

  public SubjectResponse studyClassResponse(StudyClassResponse studyClassResponse) {
    this.studyClassResponse = studyClassResponse;
    return this;
  }

   /**
   * Get studyClassResponse
   * @return studyClassResponse
  **/
  @ApiModelProperty(example = "null", value = "")
  public StudyClassResponse getStudyClassResponse() {
    return studyClassResponse;
  }

  public void setStudyClassResponse(StudyClassResponse studyClassResponse) {
    this.studyClassResponse = studyClassResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubjectResponse subjectResponse = (SubjectResponse) o;
    return Objects.equals(this.id, subjectResponse.id) &&
        Objects.equals(this.subjectName, subjectResponse.subjectName) &&
        Objects.equals(this.staffResponese, subjectResponse.staffResponese) &&
        Objects.equals(this.studyClassResponse, subjectResponse.studyClassResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, subjectName, staffResponese, studyClassResponse);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubjectResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    subjectName: ").append(toIndentedString(subjectName)).append("\n");
    sb.append("    staffResponese: ").append(toIndentedString(staffResponese)).append("\n");
    sb.append("    studyClassResponse: ").append(toIndentedString(studyClassResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

